import "./src/config/env.js";
import express from "express";
import cors from "cors";
import { fileURLToPath } from "node:url";
import { protect } from "./src/middleware/authMiddleware.js";
import { requireAttachmentAccess } from "./src/middleware/problemAccessMiddleware.js";
import { errorHandler } from "./src/utils/http.js";
import { rateLimit } from "./src/middleware/rateLimitMiddleware.js";
import authRoutes from "./src/routes/authRoutes.js";
import problemRoutes from "./src/routes/problemRoutes.js";
import locationRoutes from "./src/routes/locationRoutes.js";
import universityRoutes from "./src/routes/universityRoutes.js";
import industryRoutes from "./src/routes/industryRoutes.js";
import assignmentRoutes from "./src/routes/assignmentRoutes.js";
import teamRoutes from "./src/routes/teamRoutes.js";
import projectRoutes from "./src/routes/projectRoutes.js";
import proposalRoutes from "./src/routes/proposalRoutes.js";
import financeRoutes from "./src/routes/financeRoutes.js";
import milestoneRoutes from "./src/routes/milestoneRoutes.js";
import impactRoutes from "./src/routes/impactRoutes.js";
import ratingRoutes from "./src/routes/ratingRoutes.js";
import notificationRoutes from "./src/routes/notificationRoutes.js";
import tagRoutes from "./src/routes/tagRoutes.js";
import userRoutes from "./src/routes/userRoutes.js";
import analyticsRoutes from "./src/routes/analyticsRoutes.js";
import assistantRoutes from "./src/routes/assistantRoutes.js";
const app=express();
app.disable("x-powered-by");
app.use(cors({origin:process.env.FRONTEND_URL||"http://localhost:5173",credentials:true}));
app.use(express.json({limit:"256kb"}));
app.use((req,res,next)=>{res.set("X-Content-Type-Options","nosniff");next();});
app.use("/api/auth/login",rateLimit({limit:20,windowMs:15*60*1000}));
app.use("/api/auth/register",rateLimit({limit:20,windowMs:15*60*1000}));
app.get("/uploads/problems/:filename",protect,requireAttachmentAccess,(req,res,next)=>{
 if(!/^[a-zA-Z0-9._-]+$/.test(req.params.filename))return res.status(404).json({success:false,message:"Attachment not found"});
 res.set("Content-Disposition",'attachment; filename="'+req.params.filename+'"');
 res.sendFile(req.params.filename,{root:fileURLToPath(new URL("./uploads/problems/",import.meta.url)),dotfiles:"deny"},error=>{if(error)next(error);});
});
app.use("/api/auth",authRoutes);
app.use("/api/problems",problemRoutes);
app.use("/api/locations",locationRoutes);
app.use("/api/universities",universityRoutes);
app.use("/api/industries",industryRoutes);
app.use("/api/assignments",assignmentRoutes);
app.use("/api/teams",teamRoutes);
app.use("/api/projects",projectRoutes);
app.use("/api/proposals",proposalRoutes);
app.use("/api/finance",financeRoutes);
app.use("/api/milestones",milestoneRoutes);
app.use("/api/impact",impactRoutes);
app.use("/api/ratings",ratingRoutes);
app.use("/api/notifications",notificationRoutes);
app.use("/api/tags",tagRoutes);
app.use("/api/users",userRoutes);
app.use("/api/analytics",analyticsRoutes);
app.use("/api/assistant",assistantRoutes);
app.get("/",(req,res)=>res.send("PragatiX backend running"));
app.get("/health",(req,res)=>res.json({status:"ok"}));
app.use((req,res)=>res.status(404).json({success:false,message:"Route not found"}));
app.use(errorHandler);
export default app;
