import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, ArrowRight, Bookmark, CalendarDays, ChevronRight, Filter, Lightbulb, MapPin, Search, Send, Sparkles, Users, X } from 'lucide-react'
import samadhanSetuLogo from '../assets/samadhan-setu-logo.png'
import { problemApi } from '../lib/problemApi'
import { statusLabels } from '../lib/problemTaxonomy'
import './PublicChallenges.css'

const guestKey='pragatix-guest-problems'
const domains=['All domains','Education','Healthcare','Agriculture','Water Management','Sanitation','Environment','Rural Livelihood','Accessibility','Urban Infrastructure','Public Service Delivery','Energy','Other']
const statuses=['All statuses','Submitted','Verified','Prioritized','Assigned','In Progress','Resolved','Escalated']
const seedChallenges=[
  {id:'JH-CH-1023',title:'Smart irrigation support for water-stressed farms',description:'Small and marginal farmers need an affordable way to monitor soil moisture and schedule irrigation during irregular rainfall.',domain:'AGRICULTURE',status:'VERIFIED',peopleAffected:850,district:'Ranchi',createdAt:'2026-09-10',_count:{attachments:3,upvotes:41,comments:7}},
  {id:'JH-CH-1022',title:'Early warning for unsafe community handpump water',description:'Rural communities require a low-cost system that can flag likely contamination and support timely testing of drinking-water sources.',domain:'WATER_MANAGEMENT',status:'PRIORITIZED',peopleAffected:1200,district:'Sahebganj',createdAt:'2026-09-08',_count:{attachments:5,upvotes:56,comments:11}},
  {id:'JH-CH-1021',title:'Remote maternal health monitoring in forest villages',description:'Frontline health workers need reliable offline-first monitoring and referral support for pregnant women in remote settlements.',domain:'HEALTHCARE',status:'ASSIGNED',peopleAffected:420,district:'Latehar',createdAt:'2026-09-06',_count:{attachments:2,upvotes:38,comments:9}},
  {id:'JH-CH-1020',title:'Accessible learning material in tribal languages',description:'Students need inclusive digital and printable learning resources that work in low-connectivity environments and local languages.',domain:'EDUCATION',status:'VERIFIED',peopleAffected:2600,district:'West Singhbhum',createdAt:'2026-09-04',_count:{attachments:4,upvotes:72,comments:14}},
  {id:'JH-CH-1019',title:'Waste segregation for weekly rural markets',description:'Local bodies need a practical collection and segregation process for high-volume waste generated during weekly markets.',domain:'SANITATION',status:'SUBMITTED',peopleAffected:5000,district:'Dumka',createdAt:'2026-09-02',_count:{attachments:6,upvotes:31,comments:5}},
  {id:'JH-CH-1018',title:'Safer movement of mine vehicles in dense fog',description:'Mining communities need collision-prevention and visibility assistance for heavy vehicles operating in low-visibility conditions.',domain:'PUBLIC_SERVICE_DELIVERY',status:'IN_PROGRESS',peopleAffected:310,district:'Dhanbad',createdAt:'2026-08-29',_count:{attachments:1,upvotes:27,comments:6}},
]

const humanize=value=>(value||'OTHER').replaceAll('_',' ').replace(/\b\w/g,letter=>letter.toUpperCase())
const extractDistrict=problem=>problem.block?.district?.name || problem.district || problem.description?.match(/District: ([^\n]+)/)?.[1] || 'Jharkhand'
const departmentByDomain={AGRICULTURE:'Department of Agriculture',WATER_MANAGEMENT:'Drinking Water & Sanitation',HEALTHCARE:'Health & Family Welfare',EDUCATION:'School Education & Literacy',SANITATION:'Panchayati Raj Department',ENVIRONMENT:'Forest, Environment & Climate Change',RURAL_LIVELIHOOD:'Rural Development Department',URBAN_INFRASTRUCTURE:'Urban Development & Housing',PUBLIC_SERVICE_DELIVERY:'Administrative Reforms Department',ENERGY:'Department of Energy'}
const extractDepartment=problem=>problem.submittedBy?.department?.name || problem.department || departmentByDomain[problem.domain] || 'Citizen / Community'
const loadGuest=()=>{try{return JSON.parse(localStorage.getItem(guestKey)||'[]').map(item=>({...item,description:'Community-submitted public challenge. Open the statement to learn more.',district:'Jharkhand',peopleAffected:null,_count:{attachments:0,upvotes:0,comments:0}}))}catch{return[]}}

export default function PublicChallenges({user,onNavigate,onSignIn}){
  const [problems,setProblems]=useState([])
  const [loading,setLoading]=useState(true)
  const [notice,setNotice]=useState('')
  const [query,setQuery]=useState('')
  const [domain,setDomain]=useState('All domains')
  const [status,setStatus]=useState('All statuses')
  const [selected,setSelected]=useState(null)
  const [solutionFor,setSolutionFor]=useState(null)
  const [bookmarks,setBookmarks]=useState(()=>{try{return new Set(JSON.parse(localStorage.getItem('samadhansetu-challenge-bookmarks')||'[]'))}catch{return new Set()}})

  useEffect(()=>{
    problemApi.listPublic().then(result=>setProblems([...loadGuest(),...(result.data||[])])).catch(()=>{setProblems([...loadGuest(),...seedChallenges]);setNotice('Showing the demonstration catalogue while the challenge server is unavailable.')}).finally(()=>setLoading(false))
  },[])
  const filtered=useMemo(()=>problems.filter(problem=>{
    const matchQuery=`${problem.id} ${problem.title} ${problem.description} ${problem.domain} ${extractDistrict(problem)}`.toLowerCase().includes(query.toLowerCase())
    const matchDomain=domain==='All domains'||humanize(problem.domain)===domain
    const matchStatus=status==='All statuses'||humanize(problem.status)===status
    return matchQuery&&matchDomain&&matchStatus
  }),[problems,query,domain,status])
  const toggleBookmark=id=>setBookmarks(current=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);localStorage.setItem('samadhansetu-challenge-bookmarks',JSON.stringify([...next]));const savedProblems=problems.filter(problem=>next.has(problem.id));localStorage.setItem('samadhansetu-saved-challenges',JSON.stringify(savedProblems));return next})
  const saveConcept=event=>{event.preventDefault();const form=new FormData(event.currentTarget);const key=`samadhansetu-solution-concepts-${user?.id||'guest'}`;const current=JSON.parse(localStorage.getItem(key)||'[]');const concept={id:`CONCEPT-${Date.now()}`,problemId:solutionFor.id,problemTitle:solutionFor.title,title:form.get('title'),approach:form.get('approach'),skills:form.get('skills'),team:form.get('team'),createdAt:new Date().toISOString()};localStorage.setItem(key,JSON.stringify([concept,...current]));setSolutionFor(null);setNotice(user?'Solution concept saved. Continue development from your dashboard.':'Concept saved on this device. Sign in to collaborate with a team.')}
  const openSolution=problem=>{setSelected(null);onNavigate(`/challenges/${encodeURIComponent(problem.id)}/solution`)}

  return <div className="public-challenges">
    <header className="challenge-nav"><button onClick={()=>onNavigate('/')}><img src={samadhanSetuLogo} alt="SamadhanSetu"/></button><nav><button onClick={()=>onNavigate('/')}><ArrowLeft/>Home</button><button className="active">Challenges</button>{user?<button className="challenge-dashboard" onClick={()=>onNavigate(user.role==='CITIZEN'?'/citizen':'/organization')}>Dashboard</button>:<button className="challenge-dashboard" onClick={onSignIn}>Sign in</button>}</nav></header>
    <main>
      <section className="challenge-hero"><div><span><Sparkles/> OPEN INNOVATION CATALOGUE</span><h1>Choose a challenge.<br/><em>Build what matters.</em></h1><p>Explore public problem statements contributed by communities across Jharkhand. Research, collaborate and develop solutions with measurable social impact.</p><div><button onClick={()=>onNavigate('/citizen/submit')}>Add a new challenge <ArrowRight/></button><small>No account required to browse</small></div></div><aside><strong>{problems.length || '—'}</strong><span>public challenges</span><div><b>{new Set(problems.map(item=>item.domain)).size}</b> domains <b>{new Set(problems.map(extractDistrict)).size}</b> districts</div></aside></section>
      <section className="challenge-catalogue"><div className="catalogue-heading"><div><span>PROBLEM STATEMENTS</span><h2>Find a problem worth solving</h2></div><p>Search by challenge ID, keyword, domain or district.</p></div>
        <div className="challenge-filters"><label><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search ID, title, keyword or district…"/></label><label><Filter/><select value={domain} onChange={event=>setDomain(event.target.value)}>{domains.map(item=><option key={item}>{item}</option>)}</select></label><select value={status} onChange={event=>setStatus(event.target.value)}>{statuses.map(item=><option key={item}>{item}</option>)}</select><button onClick={()=>{setQuery('');setDomain('All domains');setStatus('All statuses')}}>Clear filters</button></div>
        {notice&&<div className="catalogue-notice">{notice}<button onClick={()=>setNotice('')}><X/></button></div>}
        <div className="catalogue-result"><span>Showing <strong>{filtered.length}</strong> challenges</span><span>Updated automatically from public submissions</span></div>
        {loading?<div className="catalogue-loading"><i/><span>Loading public challenges…</span></div>:<div className="challenge-table-wrap"><table className="challenge-table"><thead><tr><th>Challenge ID</th><th>Problem statement</th><th>District</th><th>Department / Source</th><th>Domain</th><th>Ideas</th><th>Status</th><th>Action</th></tr></thead><tbody>{filtered.map(problem=><tr key={problem.id}><td><span className="table-id">{problem.id}</span><button className={bookmarks.has(problem.id)?'table-save saved':'table-save'} onClick={()=>toggleBookmark(problem.id)} aria-label="Save challenge"><Bookmark/></button></td><td><button className="statement-link" onClick={()=>setSelected(problem)}><strong>{problem.title}</strong><span>{problem.description?.split('\n---')[0]}</span></button></td><td><span className="table-location"><MapPin/>{extractDistrict(problem)}</span></td><td><span className="table-department">{extractDepartment(problem)}</span></td><td><span className="table-domain">{humanize(problem.domain)}</span></td><td><button className="idea-count" onClick={()=>openSolution(problem)}><Lightbulb/>{problem._count?.comments||0}</button></td><td><span className={`table-status status-${problem.status?.toLowerCase()}`}>{statusLabels[problem.status]||humanize(problem.status)}</span></td><td><button className="table-action" onClick={()=>setSelected(problem)}>View <ChevronRight/></button></td></tr>)}</tbody></table></div>}
        {!loading&&!filtered.length&&<div className="catalogue-empty"><Search/><h3>No challenges match these filters</h3><p>Try a broader keyword or clear the selected filters.</p><button onClick={()=>{setQuery('');setDomain('All domains');setStatus('All statuses')}}>Clear filters</button></div>}
      </section>
    </main>
    {selected&&<div className="challenge-modal-bg" onMouseDown={()=>setSelected(null)}><section className="challenge-detail" onMouseDown={event=>event.stopPropagation()}><button className="challenge-close" onClick={()=>setSelected(null)}><X/></button><span>{selected.id} · {humanize(selected.domain)}</span><h2>{selected.title}</h2><div className="detail-meta"><span><MapPin/>{extractDistrict(selected)}</span><span><CalendarDays/>{new Date(selected.createdAt).toLocaleDateString()}</span><span><Users/>{selected.peopleAffected?.toLocaleString()||'Impact under review'} people</span></div><div className="detail-body"><h3>Problem statement</h3><p>{selected.description}</p></div><div className="detail-actions"><button onClick={()=>toggleBookmark(selected.id)}><Bookmark/> {bookmarks.has(selected.id)?'Saved':'Save challenge'}</button><button onClick={()=>openSolution(selected)}><Lightbulb/> Work on a solution</button></div></section></div>}
    {solutionFor&&<div className="challenge-modal-bg" onMouseDown={()=>setSolutionFor(null)}><section className="solution-concept" onMouseDown={event=>event.stopPropagation()}><button className="challenge-close" onClick={()=>setSolutionFor(null)}><X/></button><span>START INNOVATING</span><h2>Develop a solution concept</h2><p>For: <strong>{solutionFor.title}</strong></p><form onSubmit={saveConcept}><label>Concept title<input name="title" required placeholder="Give your solution a working title"/></label><label>Your proposed approach<textarea name="approach" required rows="5" placeholder="Explain the idea, expected impact and how it could be tested"/></label><div><label>Skills or technology<input name="skills" required placeholder="e.g. IoT, design, public health"/></label><label>Team or institution<input name="team" placeholder="Optional at concept stage"/></label></div><button><Send/> Save solution concept</button></form>{!user&&<small>Your draft will stay on this device. <button onClick={onSignIn}>Sign in</button> to access collaboration tools.</small>}</section></div>}
  </div>
}

export function SolutionIdeaPage({challengeId,user,onNavigate,onSignIn}){
  const [problem,setProblem]=useState(null)
  const [ideas,setIdeas]=useState([])
  const [loading,setLoading]=useState(true)
  const [submitting,setSubmitting]=useState(false)
  const [message,setMessage]=useState('')
  useEffect(()=>{Promise.all([problemApi.listPublic(),problemApi.listIdeas(challengeId)]).then(([problemsResult,ideasResult])=>{setProblem((problemsResult.data||[]).find(item=>item.id===challengeId)||null);setIdeas(ideasResult.data||[])}).catch(err=>setMessage(err.message)).finally(()=>setLoading(false))},[challengeId])
  const submit=async event=>{event.preventDefault();if(!user)return onSignIn();setSubmitting(true);setMessage('');const form=new FormData(event.currentTarget);try{const result=await problemApi.submitIdea(challengeId,Object.fromEntries(form));setIdeas(current=>[result.data,...current]);event.currentTarget.reset();setMessage('Your solution idea has been shared with teams working on this challenge.')}catch(err){setMessage(err.message)}finally{setSubmitting(false)}}
  return <div className="idea-page"><header className="challenge-nav"><button onClick={()=>onNavigate('/')}><img src={samadhanSetuLogo} alt="SamadhanSetu"/></button><nav><button onClick={()=>onNavigate('/challenges')}><ArrowLeft/>All challenges</button>{user?<button className="challenge-dashboard" onClick={()=>onNavigate(user.role==='CITIZEN'?'/citizen':'/organization')}>Dashboard</button>:<button className="challenge-dashboard" onClick={onSignIn}>Sign in</button>}</nav></header>{loading?<div className="idea-page-loading">Loading challenge…</div>:<main className="idea-page-main"><section className="idea-context"><span>{challengeId} · {humanize(problem?.domain)}</span><h1>{problem?.title||'Public challenge'}</h1><p>{problem?.description?.split('\n---')[0]||'Share a practical solution that can help address this community challenge.'}</p><div><span><MapPin/>{problem?extractDistrict(problem):'Jharkhand'}</span><span><Lightbulb/>{ideas.length} ideas submitted</span></div></section><div className="idea-layout"><section className="idea-form-card"><span>CONTRIBUTE AN IDEA</span><h2>What could solve this?</h2><p>Share an early idea. University teams, innovators and organisations working on this challenge will be able to review it.</p><form onSubmit={submit}><label>Idea title<input name="title" required maxLength="160" placeholder="A short, clear name for your idea"/></label><label>Proposed solution<textarea name="summary" required rows="6" placeholder="Explain how your idea works and how it addresses the problem"/></label><label>Expected community impact<textarea name="impact" rows="3" placeholder="Who benefits and what may improve?"/></label><label>Skills or technology needed<input name="skills" placeholder="e.g. IoT, civil engineering, community research"/></label><button disabled={submitting}><Send/>{submitting?'Submitting…':user?'Submit solution idea':'Sign in to submit'}</button></form>{message&&<div className={message.startsWith('Your')?'idea-success':'auth-error'}>{message}</div>}</section><section className="idea-submissions"><div><span>IDEA SUBMISSIONS</span><h2>Community thinking</h2><p>Ideas visible to everyone researching or working on this challenge.</p></div>{ideas.map(idea=><article key={idea.id}><div><span><Lightbulb/></span><p><strong>{idea.author?.name||'Citizen innovator'}</strong><small>{new Date(idea.createdAt).toLocaleDateString()} · {humanize(idea.author?.role)}</small></p></div><h3>{idea.title}</h3><p>{idea.summary}</p>{idea.impact&&<aside><strong>Expected impact</strong>{idea.impact}</aside>}{idea.skills&&<small>Skills / technology: {idea.skills}</small>}</article>)}{!ideas.length&&<div className="idea-empty"><Lightbulb/><strong>Be the first to share an idea</strong><span>Early ideas can inspire research, collaboration and better solutions.</span></div>}</section></div></main>}</div>
}
